#!/bin/bash

# Takes an MR image and a mask, generates a onepad image

cdir=$(dirname "$0")
. "$cdir"/common
cdir=$(normalpath "$cdir")

pn=$0
prog=$(basename "$pn")
comline="$cdir/$prog $*"

# parameters
inputimage=
mask=
outputimage=
while [ $# -gt 0 ]
do
    case "$1" in
	-inputimage)   inputimage="$2"; shift;;
	-mask)               mask="$2"; shift;;
	-outputimage) outputimage="$2"; shift;;
	--) shift; break;;
	-*)
	    echo >&2 \
		    "Usage: $0 -inputimage img.nii.gz -mask mask.nii.gz -outputimage onepad.nii.gz"
    exit 1;;
*)  break;;# terminate while loop
    esac
    shift
done

origwd="$PWD"
td=$(tempdir)
trap 'rm -rf \"$td\" >/dev/null 2>&1' 0
trap "cp -r \"$td\" \"$origwd\"/" 1 2 3 13 15

[[ -e $inputimage ]] || fatal "Image $inputimage does not exist"
inputimage=$(normalpath $inputimage)

outputimage=$(normalpath $outputimage)

[[ -e $mask ]] || fatal "Mask $mask does not exist"
mask=$(normalpath $mask)

cd "$td"
seg_maths $mask -bin mask-bin.nii
seg_maths $inputimage -mul mask-bin.nii masked.nii
seg_maths mask-bin.nii -dil 3 -add masked.nii $outputimage

exit 0
