#!/bin/bash

# Takes an MR image and a mask, generates a onepad image

cdir=$(dirname "$0")
. "$cdir"/common
cdir=$(normalpath "$cdir")

pn=$0
prog=$(basename "$pn")
comline="$cdir/$prog $*"

# parameters
inputimage=
mask=
outputimage=
while [ $# -gt 0 ]
do
    case "$1" in
	-inputimage)   inputimage="$2"; shift;;
	-mask)               mask="$2"; shift;;
	-outputimage) outputimage="$2"; shift;;
	-type)               type="$2"; shift;;
	--) shift; break;;
	-*)
	    echo >&2 \
		    "Usage: $0 -inputimage img.nii.gz -mask mask.nii.gz -outputimage tc3.nii.gz"
    exit 1;;
*)  break;;# terminate while loop
    esac
    shift
done

origwd="$PWD"
td=$(tempdir)
trap 'rm -rf \"$td\" >/dev/null 2>&1' 0
trap "cp -r \"$td\" \"$origwd\"/" 1 2 3 13 15

[[ -e $inputimage ]] || fatal "Image $inputimage does not exist"
inputimage=$(normalpath $inputimage)

outputimage=$(normalpath $outputimage)

[[ -e $mask ]] || fatal "Mask $mask does not exist"
mask=$(normalpath $mask)

[[ $type = "t2" ]] || type="t1"

cd $td

seg_EM -in $inputimage -out tc3raw.nii.gz -bc_out discard.nii.gz -nopriors 3 -mask $mask
#seg_maths tc3raw.nii.gz -tpmax -add $mask $crispoutput

# Get individual tc probability maps, subsample
case $type in
    t1)
	seg_maths tc3raw.nii.gz -tp 0 -mul 254 csffull.nii.gz
	resample csffull.nii.gz csf.nii.gz -size 2 2 2

	seg_maths tc3raw.nii.gz -tp 1 -mul 255 gmfull.nii.gz
	resample gmfull.nii.gz gm.nii.gz -size 2 2 2

	seg_maths tc3raw.nii.gz -tp 2 -mul 255 wm.nii.gz
	resample wm.nii.gz wm.nii.gz -size 2 2 2
	;;
    t2)
	seg_maths tc3raw.nii.gz -tp 0 -mul 255 wm.nii.gz
	resample wm.nii.gz wm.nii.gz -size 2 2 2

	seg_maths tc3raw.nii.gz -tp 1 -mul 255 gmfull.nii.gz
	resample gmfull.nii.gz gm.nii.gz -size 2 2 2

	seg_maths tc3raw.nii.gz -tp 2 -mul 254 csffull.nii.gz
	resample csffull.nii.gz csf.nii.gz -size 2 2 2
	;;
esac
	
# Pad CSF map
resample $mask maskres.nii.gz -size 2 2 2
dilation maskres.nii.gz maskdil.nii.gz -iterations 3
seg_maths csf.nii.gz -add maskdil.nii.gz csfpadded.nii.gz

# Combine into multispectral volume
seg_maths csfpadded.nii.gz -merge 2 4 gm.nii.gz wm.nii.gz -div 255 $outputimage

exit 0
