#!/bin/bash

cdir=$(dirname "$0")
. "$cdir"/maper.rc
. "$cdir"/common
cdir=$(normalpath "$cdir")

pn=$0
prog=$(basename "$pn")
comline="$cdir/$prog $*"

# parameters
mad=
target=
outdir=
ijobs="100%"
debugdir=
type="fast"
arch=bash
while [ $# -gt 0 ]
do
    case "$1" in
	-atlas)     atlas="$2"; shift;;
	-target)   target="$2"; shift;;
	-type)       type="$2"; shift;;
	-arch)       arch="$2"; shift;;
	-output)   outdir="$2"; shift;;
	-jobs)      ijobs="$2"; shift;;
	-debug)  debugdir="$2"; shift;;
	--) shift; break;;
	-*)
	    echo >&2 \
		    "Usage: $0 -atlas atlas-description.csv -target target-description.csv -type [fast|standard|oldstandard|experimental] -arch [pbs|ge|bash] -output output-directory -jobs max-parallel -debug debug-directory"
    exit 1;;
*)  break;;# terminate while loop
    esac
    shift
done

atlas=$(normalpath "$atlas")
test -e "$atlas" || fatal "Source $atlas not found"

target=$(normalpath "$target")
test -e "$target" || fatal "Target $target not found"

outdir=$(normalpath "$outdir")
test -e "$outdir" || mkdir -p "$outdir" || fatal "Creation of output directory $outdir failed" 

jobs=$(echo "$ijobs" | tr -d '%')
[[ $jobs =~ ^[0-9]+$ ]] || fatal "Non-numeric setting for -jobs"
jobs=$ijobs

if ! [[ -e "$debugdir" ]] ; then
    debugdir=
    echo "Debug directory does not exist -- intermediate output will be discarded"
fi
debugdir=$(normalpath "$debugdir")

td=$(tempdir)
if [[ -z "$debugdir" ]] ; then
    trap 'rm -rf $td >/dev/null 2>&1' 0 1 2 3 13 15
else
    trap 'cp -r $td $debugdir' 0 1 2 3 13 15
fi
origwd="$PWD"
cd "$td"

echo "$comline" >commandline.log

set -- $(grep -v '^#' "$target")
targetbase="$1" ; shift
targets="$*"
m=0
for i in $targets ; do
    (( m+=1 ))
    set -- $(echo "$i" | tr , ' ' )
    tgtname="$1" ; shift
    mkdir "$outdir"/"$tgtname" || fatal "Could not create directory $outdir/$tgtname"
    tgtoutdir="$outdir"/"$tgtname"
    tgtop="$targetbase"/"$1" ; shift
    tgttc3="$targetbase"/"$1" ; shift
    tpn="$targetbase"/"$1" ; shift
    refsegs=
    while [ $# -gt 0 ] ; do
	refsegs="$refsegs -refseg $targetbase/$1" ; shift
    done

    set -- $(cat "$atlas")
    atlasbase="$1" ; shift
    atlases="$*"
    atlasn=$#
    n=0
    for j in $atlases ; do
	(( n+=1 ))
	set -- $(echo $j | tr , ' ')
	atlname="$1" ; shift
	srcop="$atlasbase"/"$1" ; shift
	srctc3="$atlasbase"/"$1" ; shift
	spn="$atlasbase"/"$1" ; shift
	srcsegs=
	while [ $# -gt 0 ] ; do
	    srcsegs="$srcsegs -srcseg $atlasbase/$1" ; shift
	done
	echo "$cdir"/propagate -source "$srcop" -target "$tgtop" -srctc3 "$srctc3" -tgttc3 "$tgttc3" -spn "$spn" -tpn "$tpn" $srcsegs $refsegs -type $type -ensemblesize $atlasn -output "$tgtoutdir"/a$n -debug "$debugdir" >"$outdir"/a$n-t$m.sh
	echo "$outdir"/a$n-t$m.sh >>"$outdir"/job-list.sh
    done
done

cd "$outdir"
export MAPER_WORKDIR=$outdir
"$cdir"/distrib -jobs $jobs -processlist "$outdir"/job-list.sh -arch $arch

exit 0
