#!/bin/bash

msg () {
    for msgline
    do echo "$pn: $msgline" >&2
    done
}

fatal () { msg "$@" ; exit 1 ; }

tempdir () {
    : ${TMPDIR:="/tmp"}
    tdbase=$TMPDIR/$USER
    test -e $tdbase || mkdir -p $tdbase
    td=$(mktemp -d $tdbase/$(basename $0).XXXXXX) || fatal "Could not create temp dir in $tdbase"
    echo $td
}

normalpath () {
    dir=$(dirname "$1")
    bas=$(basename "$1")
    echo $(cd $dir && pwd)/$bas
}

export PATH=/work/rahec/software/niftyreg-svn355/bin:$PATH
export PATH=/work/rahec/software/niftyseg/bin:$PATH

set -e   # Terminate script at first error
