#!/bin/bash

. /etc/fsl/5.0/fsl.sh

msg () {
    for msgline
    do echo "$pn: $msgline" >&2
    done
}

fatal () { msg "$@" ; exit 1 ; }

tempdir () {
    : ${TMPDIR:="/tmp"}
    tdbase=$TMPDIR/$USER
    test -e $tdbase || mkdir -p $tdbase
    td=$(mktemp -d $tdbase/$(basename $0).XXXXXX) || fatal "Could not create temp dir in $tdbase"
    echo "$td"
}

normalpath () {
    dir=$(dirname "$1")
    bas=$(basename "$1")
    echo $(cd $dir && pwd)/$bas
}

brake() { while true ; do j=$(jobs -r | wc -l) ; test $j -lt $1 && break ; done ; }

export PATH=/home/rolf/software/niftyreg/niftyreg-svn355/build/reg-apps:$PATH
export PATH=/home/rolf/software/niftyseg/bin:$PATH

set -e   # Terminate script at first error
