#!/bin/bash

cdir=$(dirname "$0")
. "$cdir"/maper.rc
. "$cdir"/common
cdir=$(normalpath "$cdir")

pn=$0
prog=$(basename "$pn")
comline="$cdir/$prog $*"

# parameters
processlist=
datalist=
ijobs="100%"
arch="bash"
mem=7900
while [ $# -gt 0 ]
do
    case "$1" in
	-processlist)  processlist="$2"; shift;;
	-jobs)               ijobs="$2"; shift;;
	-arch)                arch="$2"; shift;;
	-mem)                  mem="$2"; shift;;
	--) shift; break;;
	-*)
	    echo >&2 \
		    "Usage: $0 -processlist list.sh -jobs max-parallel -mem RAM_mb -arch [pbs|ge|bash]"
    exit 1;;
*)  break;;# terminate while loop
    esac
    shift
done

jobs=$ijobs
[[ $jobs =~ ^[0-9]+%?$ ]] || fatal "Non-numeric setting for -jobs"

[[ -e $processlist ]] || fatal "Process list $processlist not found"
processlist=$(normalpath $processlist)

case $arch in
    ge)
	fatal "$arch not implemented"
	;;
    pbs)
	cd $MAPER_WORKDIR ; echo $PWD
	cat $processlist | while read i ; do cat $i ; done >job.conf
	n=$(cat job.conf | wc -l )
	echo qsub -J 1-$n -q med-bio -j oe "$cdir"/propagate-wrapper-$arch
	pbsjob=$(qsub -J 1-$n -q med-bio -j oe "$cdir"/propagate-wrapper-$arch)
	;;
    bash)
	echo $PATH | grep -qi pbs && fatal "PBS available -- refusing to process with bash"
	cat $processlist | parallel -j $jobs bash
    ;;
    *)
	fatal "$arch not implemented"
esac	
  
exit 0
