#!/bin/bash

#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=1:mem=3900mb


if [[ $PBS_ARRAY_INDEX -gt 0 ]] 
then
    idx=$PBS_ARRAY_INDEX
    wd=$PBS_O_WORKDIR
else
    idx=$1
    wd=$PWD
fi

set -- $(head -n $idx $wd/job.conf | tail -n 1)

$*
